/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import MainScene from "./MainScene"
import AuthRigidbody from "./AuthRigidbody"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=640;
    static height:number=1136;
    static scaleMode:string="showall";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="MainScene.scene";
    static sceneRoot:string="";
    static debug:boolean=true;
    static stat:boolean=true;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("MainScene.ts",MainScene);
        reg("AuthRigidbody.ts",AuthRigidbody);
    }
}
GameConfig.init();